version: '3.8'

services:
  rabbitmq-producer:
    build:
      context: ./rabbitmq-producer
    restart: on-failure
    ports:
      - "8081:8080"

  rabbitmq-consumer:
    build:
      context: ./rabbitmq-consumer
    restart: on-failure
    ports:
      - "8082:8080"