server:
  port: 8081

spring:
  rabbitmq:
    default-props:
      queue: ${RABBITMQ_DEFAULT_QUEUE:rotiez-queue}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
